title: Data-KungFu
email: mail@Not.yet
description: > # this means to ignore newlines until "baseurl:"
  Documentation of my learning experience, and of the projects contributions I produce along the way.

# social links
twitter_username: Twitter-is-the-scurge-of-social-media # DO NOT include the @ character, or else the build will fail!
github_username:  samurai-j-pk # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
